# Initialization

In [19]:
import pandas as pd
import numpy as np
import datetime as dt

In [20]:
sample_data = pd.read_csv("../data/raw/sampled_data.csv")
sample_data.shape

(1915511, 20)

# Data Exploration
## head-lines and data types of the columns

In [21]:
sample_data.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,Airport_fee
0,2,2023-10-29T13:05:51.000000000,2023-10-29T13:12:16.000000000,1.0,0.94,1.0,N,237,236,1,7.9,0.0,0.5,2.38,0.0,1.0,14.28,2.5,NaN,0.0
1,1,2023-04-27T17:31:16.000000000,2023-04-27T17:36:41.000000000,2.0,0.60,1.0,N,239,239,1,7.2,5.0,0.5,0.82,0.0,1.0,14.52,2.5,NaN,0.0
2,2,2023-12-26T14:53:11.000000000,2023-12-26T15:00:10.000000000,1.0,1.36,1.0,N,170,90,2,9.3,0.0,0.5,0.00,0.0,1.0,13.30,2.5,NaN,0.0
3,2,2023-09-16T21:16:24.000000000,2023-09-16T21:31:19.000000000,2.0,2.41,1.0,N,262,263,2,14.9,1.0,0.5,0.00,0.0,1.0,19.90,2.5,NaN,0.0
4,2,2023-10-22T13:05:17.000000000,2023-10-22T13:15:21.000000000,1.0,1.65,1.0,N,263,163,1,12.1,0.0,0.5,1.50,0.0,1.0,17.60,2.5,NaN,0.0
5,2,2023-08-02T13:06:33.000000000,2023-08-02T13:14:46.000000000,1.0,1.45,1.0,N,43,239,1,10.0,0.0,0.5,2.80,0.0,1.0,16.80,2.5,NaN,0.0
6,2,2023-02-17T21:46:49.000000000,2023-02-17T21:55:34.000000000,6.0,1.33,1.0,N,41,151,1,10.7,1.0,0.5,2.64,0.0,1.0,15.84,0.0,NaN,0.0
7,1,2023-08-09T17:54:59.000000000,2023-08-09T18:18:34.000000000,1.0,2.30,1.0,N,68,233,2,20.5,5.0,0.5,0.00,0.0,1.0,27.00,2.5,NaN,0.0
8,1,2023-03-19T01:14:04.000000000,2023-03-19T01:28:05.000000000,1.0,6.30,1.0,N,233,261,1,26.1,3.5,0.5,0.00,0.0,1.0,31.10,2.5,NaN,0.0
9,2,2023-12-08T00:23:04.000000000,2023-12-08T01:01:16.000000000,2.0,8.26,1.0,N,164,37,1,40.8,1.0,0.5,9.16,0.0,1.0,54.96,2.5,NaN,0.0

In [22]:
sample_data.dtypes

VendorID                   int64
tpep_pickup_datetime      object
tpep_dropoff_datetime     object
passenger_count          float64
trip_distance            float64
RatecodeID               float64
store_and_fwd_flag        object
PULocationID               int64
DOLocationID               int64
payment_type               int64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
airport_fee              float64
Airport_fee              float64
dtype: object

## Checking for duplicate entries

In [23]:
sample_data.duplicated().sum()

np.int64(0)

There are no duplicates in the sampled data

## Eliminating invalid entries:

### NA's in the ```total_amount``` column

In [24]:
print(sample_data.isnull().sum())

VendorID                       0
tpep_pickup_datetime           0
tpep_dropoff_datetime          0
passenger_count            65420
trip_distance                  0
RatecodeID                 65420
store_and_fwd_flag         65420
PULocationID                   0
DOLocationID                   0
payment_type                   0
fare_amount                    0
extra                          0
mta_tax                        0
tip_amount                     0
tolls_amount                   0
improvement_surcharge          0
total_amount                   0
congestion_surcharge       65420
airport_fee              1765876
Airport_fee               215055
dtype: int64

Since there are no null entries in the ```total_amount``` column, no observation will be deleted for now

### Zero and negative values for total amounts

#### Zero values

In [25]:
mask_null = sample_data['total_amount'] == 0
sample_data[mask_null].describe()

,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,Airport_fee
count,292.000000,279.000000,292.000000,279.000000,292.000000,292.000000,292.000000,292.0,292.0,292.0,292.0,292.0,292.0,292.0,279.0,25.0,254.0
mean,1.294521,1.007168,0.959075,7.390681,163.315068,176.058219,2.191781,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,0.456609,0.369647,3.598850,23.406051,66.847547,70.977950,1.293999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,1.000000,0.000000,0.000000,1.000000,3.000000,3.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,1.000000,1.000000,0.000000,1.000000,132.000000,138.000000,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,1.000000,1.000000,0.000000,1.000000,164.000000,193.000000,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,2.000000,1.000000,0.100000,1.000000,193.000000,237.000000,3.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,2.000000,4.000000,31.500000,99.000000,265.000000,264.000000,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
sample_data = sample_data.drop(sample_data[mask_null].index)
mask_null = sample_data['total_amount'] == 0
sample_data[mask_null]

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge, airport_fee, Airport_fee]
Index: []

There are no more zero-values on the ```total_amount``` column.

#### Negative values

As can be seen in the code chunks below, it is not possible to associate negative values in the ```total_amount``` column to a unique error in how the data was recorded. Hence the decision of dropping observations with negative values in this variable.

In [27]:
mask_neg = sample_data['total_amount'] < 0
sample_data[mask_neg].describe()

,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,Airport_fee
count,18878.0,18871.000000,18878.000000,18871.000000,18878.000000,18878.000000,18878.000000,18878.000000,18878.000000,18878.000000,18878.000000,18878.000000,18878.000000,18878.000000,18871.000000,1218.000000,17653.000000
mean,2.0,1.379312,3.010605,1.188490,160.592277,158.832980,3.356606,-20.700767,-0.990995,-0.485009,0.068241,-0.550397,-0.999184,-25.899794,-2.016454,-0.177545,-0.223885
std,0.0,0.797083,5.245125,0.661795,63.149079,70.307209,0.846337,26.807921,1.448087,0.086351,2.023392,2.372875,0.039173,28.140848,0.987472,0.436538,0.573571
min,2.0,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,-822.000000,-7.500000,-0.500000,-95.000000,-47.130000,-1.000000,-830.940000,-2.500000,-1.250000,-1.750000
25%,2.0,1.000000,0.360000,1.000000,132.000000,107.000000,3.000000,-23.300000,-1.000000,-0.500000,0.000000,0.000000,-1.000000,-27.700000,-2.500000,0.000000,0.000000
50%,2.0,1.000000,1.160000,1.000000,161.000000,161.000000,4.000000,-11.400000,-1.000000,-0.500000,0.000000,0.000000,-1.000000,-16.100000,-2.500000,0.000000,0.000000
75%,2.0,1.000000,2.850000,1.000000,230.000000,230.000000,4.000000,-5.800000,0.000000,-0.500000,0.000000,0.000000,-1.000000,-10.800000,-2.500000,0.000000,0.000000
max,2.0,6.000000,119.840000,5.000000,265.000000,265.000000,4.000000,0.000000,0.000000,0.500000,96.800000,0.000000,1.000000,-0.090000,0.000000,0.000000,0.000000

In [28]:
sample_data[mask_neg].sort_values(by = 'extra', ascending = False).head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,Airport_fee
1137,2,2023-07-06T10:11:56.000000000,2023-07-06T10:23:56.000000000,1.0,1.11,1.0,N,162,170,4,-11.4,0.0,-0.5,0.0,0.0,-1.0,-15.4,-2.5,NaN,0.0
1915381,2,2023-11-28T14:56:18.000000000,2023-11-28T15:18:11.000000000,1.0,1.99,1.0,N,114,170,2,-19.8,0.0,-0.5,0.0,0.0,-1.0,-23.8,-2.5,NaN,0.0
1914572,2,2023-12-16T10:55:47.000000000,2023-12-16T10:58:54.000000000,1.0,0.89,1.0,N,263,75,4,-5.8,0.0,-0.5,0.0,0.0,-1.0,-9.8,-2.5,NaN,0.0
1914667,2,2023-12-08T12:06:23.000000000,2023-12-08T12:16:16.000000000,1.0,1.78,1.0,N,234,161,4,-11.4,0.0,-0.5,0.0,0.0,-1.0,-15.4,-2.5,NaN,0.0
1915078,2,2023-07-06T10:04:54.000000000,2023-07-06T10:15:26.000000000,1.0,1.05,1.0,N,230,68,4,-10.7,0.0,-0.5,0.0,0.0,-1.0,-14.7,-2.5,NaN,0.0
1915091,2,2023-08-24T12:15:42.000000000,2023-08-24T12:23:18.000000000,1.0,1.11,1.0,N,234,158,4,-8.6,0.0,-0.5,0.0,0.0,-1.0,-12.6,-2.5,NaN,0.0
961,2,2023-05-21T17:54:08.000000000,2023-05-21T18:26:15.000000000,1.0,11.09,1.0,N,146,220,4,-47.1,0.0,-0.5,0.0,0.0,-1.0,-51.1,-2.5,NaN,0.0
1517337,2,2023-05-18T02:14:46.000000000,2023-05-18T02:19:10.000000000,1.0,0.44,5.0,N,148,148,4,-10.0,0.0,0.0,0.0,0.0,-1.0,-13.5,-2.5,NaN,0.0
1517638,2,2023-02-28T11:03:28.000000000,2023-02-28T11:09:28.000000000,1.0,0.92,1.0,N,239,239,4,-7.2,0.0,-0.5,0.0,0.0,-1.0,-11.2,-2.5,NaN,0.0
1517812,2,2023-11-11T15:44:18.000000000,2023-11-11T16:01:37.000000000,1.0,2.24,1.0,N,164,79,4,-17.0,0.0,-0.5,0.0,0.0,-1.0,-21.0,-2.5,NaN,0.0

In [29]:
sample_data = sample_data.drop(sample_data[mask_neg].index)
mask_neg = sample_data['total_amount'] < 0
sample_data[mask_neg]

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge, airport_fee, Airport_fee]
Index: []

## Creating auxiliar columns
In the next chunks, we will be creating columns that register the amount of seconds between the engagement and disengagement of the taximeter and a new total amount column that register the value with tips and extra charges discounted (once the tips are registered only for one of the payment methods and considering that it is not possible to know what the extra values are standing for).

In [30]:
# Converting the columns tpep_pickup_datetime and tpep_dropoff_datetime to date_time objects
sample_data['tpep_pickup_datetime'] = pd.to_datetime(sample_data['tpep_pickup_datetime'])
sample_data['tpep_dropoff_datetime'] = pd.to_datetime(sample_data['tpep_dropoff_datetime'])

# New column `trip_duration`sam
sample_data['trip_duration'] = (sample_data['tpep_dropoff_datetime'] - sample_data['tpep_pickup_datetime']).dt.total_seconds()

# New column `ttl_am_without_tips`
sample_data['ttl_am_without_tips'] = sample_data['total_amount'] - sample_data['tip_amount'] - sample_data['extra']
sample_data = sample_data.drop(['total_amount', 'tip_amount', 'extra'], axis=1)
sample_data.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,mta_tax,tolls_amount,improvement_surcharge,congestion_surcharge,airport_fee,Airport_fee,trip_duration,ttl_am_without_tips
0,2,2023-10-29 13:05:51,2023-10-29 13:12:16,1.0,0.94,1.0,N,237,236,1,7.9,0.5,0.0,1.0,2.5,NaN,0.0,385.0,11.9
1,1,2023-04-27 17:31:16,2023-04-27 17:36:41,2.0,0.60,1.0,N,239,239,1,7.2,0.5,0.0,1.0,2.5,NaN,0.0,325.0,8.7
2,2,2023-12-26 14:53:11,2023-12-26 15:00:10,1.0,1.36,1.0,N,170,90,2,9.3,0.5,0.0,1.0,2.5,NaN,0.0,419.0,13.3
3,2,2023-09-16 21:16:24,2023-09-16 21:31:19,2.0,2.41,1.0,N,262,263,2,14.9,0.5,0.0,1.0,2.5,NaN,0.0,895.0,18.9
4,2,2023-10-22 13:05:17,2023-10-22 13:15:21,1.0,1.65,1.0,N,263,163,1,12.1,0.5,0.0,1.0,2.5,NaN,0.0,604.0,16.1

In [31]:
sample_data.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,mta_tax,tolls_amount,improvement_surcharge,congestion_surcharge,airport_fee,Airport_fee,trip_duration,ttl_am_without_tips
count,1.896341e+06,1896341,1896341,1.830941e+06,1.896341e+06,1.830941e+06,1.896341e+06,1.896341e+06,1.896341e+06,1.896341e+06,1.896341e+06,1.896341e+06,1.896341e+06,1.830941e+06,148392.000000,1.682549e+06,1.896341e+06,1.896341e+06
mean,1.736500e+00,2023-07-02 20:38:28.002883072,2023-07-02 20:55:58.788383232,1.370308e+00,4.229512e+00,1.654377e+00,1.651864e+02,1.640766e+02,1.163214e+00,2.000125e+01,4.953771e-01,6.014786e-01,9.992438e-01,2.309607e+00,0.109507,1.466620e-01,1.050786e+03,2.394493e+01
min,1.000000e+00,2002-12-31 23:41:25,2003-01-01 01:34:33,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-4.077000e+01,-5.000000e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,-4.437000e+03,0.000000e+00
25%,1.000000e+00,2023-04-02 16:52:52,2023-04-02 17:12:38,1.000000e+00,1.050000e+00,1.000000e+00,1.320000e+02,1.140000e+02,1.000000e+00,9.300000e+00,5.000000e-01,0.000000e+00,1.000000e+00,2.500000e+00,0.000000,0.000000e+00,4.610000e+02,1.260000e+01
50%,2.000000e+00,2023-06-27 15:04:16,2023-06-27 15:21:32,1.000000e+00,1.800000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,1.350000e+01,5.000000e-01,0.000000e+00,1.000000e+00,2.500000e+00,0.000000,0.000000e+00,7.620000e+02,1.710000e+01
75%,2.000000e+00,2023-10-06 20:21:42,2023-10-06 20:39:49,1.000000e+00,3.400000e+00,1.000000e+00,2.340000e+02,2.340000e+02,1.000000e+00,2.228000e+01,5.000000e-01,0.000000e+00,1.000000e+00,2.500000e+00,0.000000,0.000000e+00,1.244000e+03,2.590000e+01
max,6.000000e+00,2023-12-31 23:59:51,2024-01-02 20:13:25,9.000000e+00,1.484068e+05,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,1.875030e+05,5.316000e+01,1.876500e+02,1.000000e+00,2.500000e+00,1.250000,1.750000e+00,5.482250e+05,1.875114e+05
std,4.457672e-01,NaN,NaN,8.933129e-01,2.170321e+02,7.514610e+00,6.400893e+01,6.983715e+01,5.080791e-01,1.373746e+02,6.194003e-02,2.194154e+00,2.494904e-02,6.631226e-01,0.353402,4.744612e-01,2.518235e+03,1.375948e+02

Observe, now, that there are negative values in columns ```fare_amount```, ```mta_tax```, ```trip_duration```, and ```ttl_am_without_tips``` and rides with ```trip_distance``` set to zero. For the sake of the quality of the data we'll use in further modeling and analysis, the observations with any of this anomalies will be dropped.

In [32]:
mask_anomalies = (sample_data['ttl_am_without_tips'] <= 0) | (sample_data['trip_duration'] <= 0) | (sample_data['mta_tax'] < 0) | (sample_data['fare_amount'] <= 0) | (sample_data['trip_distance'] <= 0)
sample_data = sample_data.drop(sample_data[mask_anomalies].index)
sample_data.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,mta_tax,tolls_amount,improvement_surcharge,congestion_surcharge,airport_fee,Airport_fee,trip_duration,ttl_am_without_tips
count,1.859321e+06,1859321,1859321,1.809083e+06,1.859321e+06,1.809083e+06,1.859321e+06,1.859321e+06,1.859321e+06,1.859321e+06,1.859321e+06,1.859321e+06,1.859321e+06,1.809083e+06,146653.000000,1.662430e+06,1.859321e+06,1.859321e+06
mean,1.743154e+00,2023-07-02 03:58:26.944839680,2023-07-02 04:16:03.183192320,1.370942e+00,4.312215e+00,1.583017e+00,1.652607e+02,1.641151e+02,1.167207e+00,1.988165e+01,4.968088e-01,6.033160e-01,9.995532e-01,2.323203e+00,0.109348,1.464958e-01,1.056238e+03,2.383443e+01
min,1.000000e+00,2002-12-31 23:41:25,2003-01-01 01:34:33,0.000000e+00,1.000000e-02,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,1.000000e+00,1.010000e+00
25%,1.000000e+00,2023-04-02 01:14:45,2023-04-02 01:29:34,1.000000e+00,1.100000e+00,1.000000e+00,1.320000e+02,1.140000e+02,1.000000e+00,9.300000e+00,5.000000e-01,0.000000e+00,1.000000e+00,2.500000e+00,0.000000,0.000000e+00,4.660000e+02,1.260000e+01
50%,2.000000e+00,2023-06-26 10:04:31,2023-06-26 10:25:09,1.000000e+00,1.810000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,1.350000e+01,5.000000e-01,0.000000e+00,1.000000e+00,2.500000e+00,0.000000,0.000000e+00,7.650000e+02,1.710000e+01
75%,2.000000e+00,2023-10-06 06:04:13,2023-10-06 06:18:43,1.000000e+00,3.480000e+00,1.000000e+00,2.340000e+02,2.340000e+02,1.000000e+00,2.190000e+01,5.000000e-01,0.000000e+00,1.000000e+00,2.500000e+00,0.000000,0.000000e+00,1.247000e+03,2.550000e+01
max,6.000000e+00,2023-12-31 23:59:51,2024-01-02 20:13:25,9.000000e+00,1.484068e+05,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,1.875030e+05,5.316000e+01,1.876500e+02,1.000000e+00,2.500000e+00,1.250000,1.750000e+00,3.981870e+05,1.875114e+05
std,4.412911e-01,NaN,NaN,8.936552e-01,2.191812e+02,7.124615e+00,6.385281e+01,6.977759e+01,4.903518e-01,1.386574e+02,5.573723e-02,2.189824e+00,1.795062e-02,6.408856e-01,0.353170,4.742277e-01,2.477015e+03,1.388787e+02

## Looking for and eliminating invalid trips

Let us define what we'll call an invalid trip: we'll consider a invalid trip one that satisfies all the following requirements:
- same ID in ```pulocationid``` and ```dolocationid```
- less than 60s long

In [36]:
mask_inv = (sample_data['PULocationID'] == sample_data['DOLocationID']) & (sample_data['trip_duration'] < 60)
sample_data = sample_data.drop(sample_data[mask_inv].index)

## Checking for invalit inputs in columns ```vendorid```, ```ratecodeid```, ```payment_type```.

In the next chunks, we'll be looking for entries outside the specified in the documentation provided by TLC (see 'README.md' file for more information)
Observe that both ```vendorid``` and ```payment_type``` have invalid entries, the invalid entries in both columns will be drop

In [37]:
vendorid_un = sample_data['VendorID'].unique().tolist()
ratecodeid_un = sample_data['RatecodeID'].unique().tolist()
payment_type_un = sample_data['payment_type'].unique().tolist()

print("Unique vendorid's: ", sorted(vendorid_un))
print("Unique ratecodeid's: ", sorted(ratecodeid_un))
print("Unique payment_type's: ", sorted(payment_type_un))

Unique vendorid's:  [1, 2, 6]
Unique ratecodeid's:  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 99.0, nan]
Unique payment_type's:  [0, 1, 2, 3, 4]

Consider the choice made before of not dropping NA's in the ratecode_id column till further exploration, hence, the invalid entries in this case will be the ones which vendor id was assingned as 6.

In [38]:
# Invalid entries
mask_inv_vid = sample_data['VendorID'] == 6
sample_data = sample_data.drop(sample_data[mask_inv_vid].index)

# Saving dataframe as a csv file for later use

In [39]:
sample_data.to_csv('../data/clean/clean_data.csv', index=False)